# Generated by Django 4.2.17 on 2024-12-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_transaction_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.5, max_digits=10),
            preserve_default=False,
        ),
    ]
