# Generated by Django 4.2.17 on 2025-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
