# Generated by Django 4.2.17 on 2025-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_masterfile',
            name='mobile',
            field=models.CharField(default='7008080545', max_length=10),
            preserve_default=False,
        ),
    ]
